module XamlGeneration

open XmlGeneration
open System
open System.IO
open Xunit.Sdk

let doc =
    XDocument (XDeclaration "1.0" "UTF-8" "yes") [
        XComment "This document was automatically generated by a configuration script."
        XElement "UserControl" [
            XElement "Grid" [
                XElement "Grid.RowDefinitions" [
                  XElement "RowDefinition" [ XAttribute "Height" "40"]
                  XElement "RowDefinition" [ XAttribute "Height" "40"]
                  XElement "RowDefinition" [ XAttribute "Height" "40"]
                ]
                XElement "GenerationDate" [DateTime.UtcNow.ToString("s")]
                XElement "IndexedBy" ["UNKNOWN"]
                XElement "IndexedOn" ["UNKNOWN"]
                XElement "ScanInfo" [
                    XElement "IpAddress" ["UNKNOWN"]
                    XElement "MachineName" ["UNKNOWN"]
                    XElement "NumberOfBlankPages" ["0"]
                ]
            ]
        ]
    ]
 
let saveToFile (fileName : string) = doc.Save(fileName = fileName)

//let saveToFile fileName = 
//  use fileStream = new FileStream(fileName, FileMode.Create, System.IO.FileAccess.Write)
//  ms.CopyTo(fileStream)
